# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c6b0e502a06b1577597ab0e8a5531c08fa8edf4fddc55cc19ca435499c107f425cacae574b422fd8090747ab2968c197d11fecf990bd24b29434b7b489ede1

test:
  secret_key_base: bda1b3fa7089935822708b60962f9e04b36a000dfe099e15255f2822261ae4ce514efb98f8e9d4fd9f8aa5f2e7aa972b6e930939551a21cae1f6b2bb469152eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
